CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(50) NOT NULL,
  profile_image_url VARCHAR(255),
  status_message VARCHAR(255),
  deleted BOOLEAN DEFAULT 0,
  joined_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE channels (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  creator INT NOT NULL,
  link VARCHAR(255) UNIQUE,
  max_capacity INT DEFAULT 100,
  deleted BOOLEAN DEFAULT 0,
  created_at DATETIME,
  FOREIGN KEY (creator) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE chats (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  sender INT NOT NULL,
  channel INT NOT NULL,
  created_at DATETIME,
  FOREIGN KEY (sender) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (channel) REFERENCES channels(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE follows (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  follower INT NOT NULL,
  followee INT NOT NULL,
  followed_at DATETIME,
  FOREIGN KEY (follower) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (followee) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE block (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  blocker INT NOT NULL,
  blocked INT NOT NULL,
  blocked_at DATETIME,
  FOREIGN KEY (blocker) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (blocked) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
